apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: solidserver
  namespace: solidserver
spec:
  dnsNames:
    - www.solidserver.cloud
  secretName: solidserver-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer