
apiVersion: v1
kind: Namespace
metadata:
  name: solidserver



---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  name: solidserver
  namespace : solidserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: solidserver-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: solidserver-deployment

    spec:
      containers:
        - image: solidproject/community-server:latest
          name: solidserver-deployment
          imagePullPolicy: Always
          args: 
            - "-b"
            - "http://www.ordinasolid.cloud"
            - "-t"
            - "-l"
            - "info"
          ports:
            - containerPort: 3000
          resources: {}
          
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: solid-file-manager
  namespace: solidserver
spec: 
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: solid-file-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solid-file-manager
    spec:
      containers:
        - image: maaktdeesuit123/css-filemanager:latest
          name: solid-file-manager
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources: {}
status: {}                        

---


apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  name: service-solidserver
  namespace: solidserver
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort    
  selector:
    app.kubernetes.io/name: solidserver-deployment


---

apiVersion: v1
kind: Service
metadata:
  name: solid-file-manager-service
  namespace: solidserver
spec: 
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: solid-file-manager      

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: solidserver
  name: ingress-solidserver
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  tls:
  - hosts:
    - www.ordinasolid.cloud
    secretName: solidserver-tls
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-solidserver
              port:
                number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: solidserver
  name: ingress-solid-file-manager
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  tls:
  - hosts:
    - filemanager.ordinasolid.cloud
    secretName: solidserver-tls
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: solid-file-manager-service
              port:
                number: 8000

---

